export const petDATA = [
    {
        id:'1',
        dogName:'Aino',
        dogAge:'2',
        dogImage: require( './picture/new-dog-image-1.jpg'),
    },
    {
    id:'2',
    dogName:'Tessu',
    dogAge:'5',
    dogImage:require('./picture/new-dog-image-2.jpg'),
    },

    {
        id:'3',
        dogName:'Sandra',
        dogAge:'10',
        dogImage: require('./picture/new-dog-image-3.jpg'),
    },

    {
        id:'4',
        dogName:'Velho',
        dogAge:'8',
        dogImage:require('./picture/new-dog-image-4.jpg'),
    },
    {
        id:'5',
        dogName:'Feya',
        dogAge:'6',
        dogImage:require('./picture/new-dog-image-5.jpg'),
    },
    {
        id:'6',
        dogName:'Drago',
        dogAge:'9',
        dogImage:require('./picture/new-dog-image-6.jpg'),
    },
    {
        id:'7',
        dogName:'Samu',
        dogAge:'7',
        dogImage:require('./picture/new-dog-image-7.jpg'),
    },
    {
        id:'8',
        dogName:'Viivi',
        dogAge:'1',
        dogImage:require('./picture/new-dog-image-8.jpg'),
    },
    {
        id:'9',
        dogName:'Bertta',
        dogAge:'2',
        dogImage:require('./picture/new-dog-image-9.jpg'),
    },
    {
        id:'10',
        dogName:'Laki',
        dogAge:'12',
        dogImage:require('./picture/new-dog-image-10.jpg'),
    },
    {
        id:'11',
        dogName:'Peppi',
        dogAge:'5',
        dogImage:require('./picture/new-dog-image-11.jpg'),
    },
    {
        id:'12',
        dogName:'Kingis',
        dogAge:'6',
        dogImage:require('./picture/new-dog-image-12.jpg'),
    },
    {
        id:'13',
        dogName:'Daisy',
        dogAge:'4',
        dogImage:require('./picture/new-dog-image-13.jpg'),
    },
    {
        id:'14',
        dogName:'Helmi',
        dogAge:'9',
        dogImage:require('./picture/new-dog-image-14.jpg'),
    },
    {
        id:'15',
        dogName:'Nekku',
        dogAge:'8',
        dogImage:require('./picture/new-dog-image-15.jpg'),
    },
    {
        id:'16',
        dogName:'Osku',
        dogAge:'7',
        dogImage:require('./picture/new-dog-image-16.jpg'),
    },
]