export const petDATA = [
    {
        id:'1',
        dogName:'Aino',
        dogAge:'2',
        dogBreed: 'Sekarotuinen',
        dogImage: require( './picture/new-dog-image-1.jpg'),
        dogInfo:'Aino on 2-vuotias nuori koiran alku, joka etsii kotia maalta. Aino ei sovellu luonteensa vuoksi kerrostaloon, eikä myöskään lapsiperheeseen. Aino on oppinut suomessa kotihoidossa ollessaan sisäsiistiksi ja on hyvin leikkisä ja ihmisrakas kaveri, lapsien kanssa kuitenkaan ei oikein tule toimeen. Aino on tullut hyvin toimeen muiden koirien kanssa kotihoidossa ollessaan. Mielellään adoptoisimme Ainon kotiin, jossa on valmiiksi toinen koira kaveri. Aino ei ole tavannut ollenkaan kissoja, joten mielellään talous ilman kissoja. Jos kiinnostuit Ainosta ja olet valmis antamaan hänelle ansaitsemansa kodin täytä yhteystietolomake. ',
        dogHealthInfo:'Rokotettu rokotusohjelman mukaisesti, madotettu ja sirutettu. Aino on rekisteröity ruokaviraston rekisteriin. Aino on kastroitu.',
    },
    {
        id:'2',
        dogName:'Tessu',
        dogAge:'5',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-2.jpg'),
        dogInfo:'Tessu on 5-vuotias rauhallinen uroksen alku, joka rakastaa rauhallisten lenkkeilyjen lisäksi kotona sohvalla makaamista luottoihmisensä kanssa. Tessu on vähän varautunut uusien ihmisten kanssa, mutta rauhallisen tutustumisen jälkeen uskaltautuu aika nopeasti haistelemaan uutta tuttavuutta. Kesäisin Tessu on kova uimari, joten olisi plussaa, jos olisi mahdollista silloin tällöin käydä jossain viilentymässä. Tessu on hyvin hiljainen yksin ollessaan, eikä välitä ylimääräisistä äänistä, joten hän soveltuu hyvin myös kerrostalo asumiseen. ',
        dogHealthInfo:'Rokotettu rokotusohjelman mukaisesti, madotettu ja sirutettu. Tessu on rekisteröity ruokaviraston rekisteriin.',
    },

    {
        id:'3',
        dogName:'Sandra',
        dogAge:'10',
        dogBreed: 'Sekarotuinen',
        dogImage: require('./picture/new-dog-image-3.jpg'),
        dogInfo:'Sandra on jo elämää nähnyt hieno rouva, joka pitää herkuttelusta ja rapsuttelusta. Sandra onkin hyvin sosiaalinen ja tulee kaikkien kanssa toimeen, niin ihmisten kuin muiden koirien. Sandra on myös asunut aikaisemmin kissojen kanssa, mutta ei näiden tekemisistä juuri välitä ja osaa antaa niille hyvin tilaa. Ikänsä vuoksi Sandralle paras olisi talo vähäisillä kerroksilla, ehkä mieluiten kerrostalo hissillä, koska iän myötä rappusten kulkeminen on jo vähän vaikeutunut. ',
        dogHealthInfo:'Rokotettu rokotusohjelman mukaisesti, madotettu ja sirutettu. Sandra on rekisteröity ruokaviraston rekisteriin.',
    },

    {
        id:'4',
        dogName:'Velho',
        dogAge:'8',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-4.jpg'),
        dogInfo:'Tämä Velho poika on varsinainen ikiliikkuja ja tuntuu, että hän ei olisi päivääkään yli vuoden iän. Hän on todella ketterä hyppimään eri paikkoihin, joksikin täytyy olla vähän varuillaan mitä jättää pöydälle, sillä Velho on myös todella kiinnostunut kaikenlaisesta syötävästä. Voitkin siis olettaa jääkaapille mentäessä, että saat aina tämän nelijalkaisen kaveriksesi. Velho tulee todella hyvin toimeen lapsien kanssa ja osaa olla heidän kanssaan varovainen, joten hän sopii täydellisesti lapsiperheeseen. Velho tulee parhaiten toimeen oman kokoisten koirien kanssa, mutta pelkää jonkin verran isoja koiria, joten kannattaa välttää turhia kohtaamisia näiden kanssa. ',
        dogHealthInfo:'Rokotettu rokotusohjelman mukaisesti, madotettu ja sirutettu. Velho on rekisteröity ruokaviraston rekisteriin.',
    },
    {
        id:'5',
        dogName:'Feya',
        dogAge:'6',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-5.jpg'),
        dogInfo:'',
        dogHealthInfo:'Rokotettu rokotusohjelman mukaisesti, madotettu ja sirutettu. Velho on rekisteröity ruokaviraston rekisteriin.',
    },
    {
        id:'6',
        dogName:'Draco',
        dogAge:'9',
        dogBreed: 'Labradorinnoutaja',
        dogImage:require('./picture/new-dog-image-6.jpg'),
        dogInfo:'',
        dogHealthInfo:'Rokotettu rokotusohjelman mukaisesti, madotettu ja sirutettu. Velho on rekisteröity ruokaviraston rekisteriin.',
    },
    {
        id:'7',
        dogName:'Samu',
        dogAge:'7',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-7.jpg'),
        dogInfo:'',
        dogHealthInfo:'Rokotettu rokotusohjelman mukaisesti, madotettu ja sirutettu. Velho on rekisteröity ruokaviraston rekisteriin.',
    },
    {
        id:'8',
        dogName:'Viivi',
        dogAge:'1',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-8.jpg'),
        dogInfo:'',
        dogHealthInfo:'Rokotettu rokotusohjelman mukaisesti, madotettu ja sirutettu. Velho on rekisteröity ruokaviraston rekisteriin.',
    },
    {
        id:'9',
        dogName:'Bertta',
        dogAge:'2',
        dogBreed: 'Boxer',
        dogImage:require('./picture/new-dog-image-9.jpg'),
        dogInfo:'Bertta on kaksivuotias sekarotuinen narttu koira. Hän on tullut Suomeen kotihoitoon lokakuussa 2022 Romanian koiratarhalta. Bertta on sopeutunut hyvin kotihoitopaikkaansa ja nyt olisi aika tarjota hänelle pysyvämpi koti. Iloinen ja leikkisä, välillä vähän riiviömäinen nuori koira kaipaakin johdonmukaista omistajaa, jolla on aikaa ja tahtoa oppia uusia asioita yhdessä. Bertta ei siis sovellu ehkä aivan ensimmäiseksi koiraksi. Hän on ollut kotihoidossa kerrostalossa, joten soveltuu myös sellaiseen asumiseen. Ei lapsiperheeseen, eikä kissatalouteen. Toisen vanhemman koiran kaveriksi hän olisi varmasti oikein oiva kaveri.',
        dogHealthInfo:'Bertta on rokotettu sekä madotettu asianmukaisesta. Tiedettävästi terve, sekä Bertta on kastroitu Suomeen tuotaessa. Sirutettu ja rekisteröity ruokaviraston viranomaisrekisteriin.',
    },
    {
        id:'10',
        dogName:'Laki',
        dogAge:'12',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-10.jpg'),
        dogInfo:'Laki on ja vähän enemmän elämää nähnyt seniori koira ja onkin kiitettävän 12 vuoden iässä. Hän etsii leppoisia eläkepäiviä tarjoavaa kotia. Hänellä oli Suomessa aiempi koti, mutta edellisen omistajan terveyden tilanteen huonontuessa joutui hän koirasta luopumaan. Tarjoamme häntä mielellään ainoaksi koiraksi, koska välillä muut koirat tuottavat haasteita. Laki on puhdasrotuinen beagle ja aikoinaan häntä onkin metsästyskoirana käytetty. Pyydämme hakijaa ottamaan huomioon koiran vanhan iän ja miettimään tarkoin onko resursseja tarjota vanhemmalle koiralle kotia, jolla todennäköisesti esiintyy jos minkälaista vanhuuden tuomaa vaivaa.',
        dogHealthInfo:'Rokotettu, madotettu ja sirutettu. Rekisteröity kennelliittoon. Ei kastroitu.',
    },
    {
        id:'11',
        dogName:'Peppi',
        dogAge:'5',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-11.jpg'),
        dogInfo:'Peppi asustaa tällä hetkellä Suomessa kotihoitopaikassaan. Hänet on tuotu Venäjältä marraskuussa 2023. Peppi on 5 vuoden ikäinen pieni sekarotuinen koira. Hänen taustoistaan ei ole tarkemmin tietoa. Hän tulee loistavasti toimeen muiden koirien kanssa ja kotihoitopaikassaan on myös tutustunut kissoihin. Jotenka muut eläimet eivät ole ongelma. Peppi on tottunut myös hyvin kaupunki ympäristöön ja kerrostalonkaan äänet eivät häntä pelota. Koulutus on vielä koiralla kesken, joten pyydämme ottamaan tämän huomioon. Aluksi todella arka ja pelokas pieni koira on osoittautunut kuitenkin uuteen ympäristöön tottuessaan todella rohkeaksi ja uteliaaksi kaveriksi.',
        dogHealthInfo:'Rokotukset asianmukaisesti annettu sekä madotettu ja sirutettu. Rekisteröity ruokaviraston viranomaisrekisteriin ja hänet on kastroitu.',
    },
    {
        id:'12',
        dogName:'Kingis',
        dogAge:'6',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-12.jpg'),
        dogInfo:'Kingis on Romanian kaduilta löydettu kulkukoira eikä hänen taustoistaan ole tarkempia tietoja. Kingis on asunut Romanian koiratarhalla useita vuosia jo 2020 lähtien. Nyt hänet on kuitenkin tuotu Suomeen kotihoitoon ja etsii kotia Suomesta. Kingis on hyvin arka ja tarjoamme häntä sellaiseen kotiin jossa ei olisi muita eläimiä. Hänellä on selvästi jotain trauma peräisiä pelkotiloja ja esimerkiksi kovat äänet pelottavat häntä hyvin paljon. Rauhallisen tutustumisen jälkeen hän on kuitenkin kotihoidossa osoittautunut hyvin reippaaksi kaveriksi. Vaikka hän on jo 6-vuotias koira on hän hyvin oppivainen ja varmasti hyvällä koulutuksella pääsee pitkälle. Joten emme suosittele häntä ihan ensimmäiseksi koiraksi vaan sellaiseen perheeseen, jossa on jo jotain osaamista koirista. Ei lapsiperheeseen.',
        dogHealthInfo:'Rokotukset ajantassalla, sirutettu ja rekisteröity ruokaviraston rekisteriin. Kastroitu ja madotettu.',
    },
    {
        id:'13',
        dogName:'Daisy',
        dogAge:'4',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-13.jpg'),
        dogInfo:'Daisy on 4-vuotias puhdasrotuinen havannankoira. Asunut koko ikänsä Suomessa, mutta joutunut lähtemään kodistaan omistajan poismenon vuoksi. Daisy on hyvin energinen ja leikkisä tapaus. Kodiksi sopii koti jossa on muita eläimiä ja hän soveltuu tietojemme mukaan myös lapsiperheeseen. Daisy on hyvin peruskoulutettu, mutta oppii varmasti mielellään uusia temppuja. Daisy on ollut kodittomana vasta ihan muutamia viikkoja, joten jos kiinnostuit otathan pikaisesti yhteyttä, että tämä neiti pääsisi jatkamaan iloista kotielämää.',
        dogHealthInfo:'Rokotettu, sirutettu ja madotettu. Rekisteröity kennelliittoon. Ei kastroitu.',
    },
    {
        id:'14',
        dogName:'Helmi',
        dogAge:'9',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-14.jpg'),
        dogInfo:'Helmi, 9-vuotias sekarotuinen narttu. Hän on alunperin tullut Venäjän koiratarhalta Suomeen. Helmi asuikin Suomessa useamman vuoden omassa kotonaan, mutta omistajan elämäntilanteen muuttuessa joutui hän koirasta luopumaan. Helmi on hyvin rauhallinen ja omista oloistaan nauttiva jo vähän elämää nähnyt koira. Hän sopisikin ainoaksi koiraksi ja soveltuu myös kaupunkielämään. Olisiko sinulla tarjota tälle aivan ihana luontoiselle ja kiltille Helmille koti? ',
        dogHealthInfo:'Helmi on rokotettu ja sirutettu sekä madotettu. Rekisteröity ruokaviraston rekisteriin. Kastroitu. Helmillä on todenäkköistä ruoka-aineallergiaa, joten kanaruoka missään muodossa ei hänelle sovi. ',
    },
    {
        id:'15',
        dogName:'Nekku',
        dogAge:'8',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-15.jpg'),
        dogInfo:'Nekku on 8-vuotias narttu koira ja Suomeen tullut Romanian koiratarhalta. Hänen taustoistaan tiedetään sen verran, että entinen omistaja on hänet tarhalle tuonut ja sinne jättänyt huono kuntoisena. Nekku on joutunut Romaniassa ollessaan useisiin hoitotoimenpiteisiin, mutta nykyään voi oikein hyvin tilanteeseen nähden. Hän on Suomessa kotihoidossa rauhallisessa omakotitalossa maaseudulla ja on sinne sopeutunut oikein hyvin. Nekku on tottunut myös siellä ollessaan muihin koiriin ja lapsiin. Olisi kuitenkin aika, että Nekku pääsisi omaan rakastavaan kotiin mihin hän on joskus tottunutkin. Hän luottaa helposti ihmiseen traumoistaan huolimatta.',
        dogHealthInfo:'Rokotettu, sirutettu ja madotettu. Rekisteröity ruokaviraston viranomaisrekisteriin. Nekulla on aiemmin romaniassa ollessaan murtunut varvas joka on sitemmin amputoitu pois. Tämä ei vaikeuta koiranelämää millään tavalla.',
    },
    {
        id:'16',
        dogName:'Osku',
        dogAge:'7',
        dogBreed: 'Sekarotuinen',
        dogImage:require('./picture/new-dog-image-16.jpg'),
        dogInfo:'Osku on vielä Romanian koiratarhalla omaa kotia odottava 7-vuotias uros koira. Hän on elänyt suurimman osan elämästään tarhalla ja olisi jo pojan aika päästä omaan kotiinsa. Osku on Romanian kaduilta löydetty oletettavasti kulkukoira. Oskua ei ole peruskoulutettu, joten pyydämme ottamaan tämän huomioon hänestä kiinnostuneet hakijat. Tarhalla Osku on ollut oikein leikkisä persoona ja nauttii koirakavereidensa seurasta. Hän etenkin nauttii ihmisen läsnäolosta. Joten oma koti alkaa olla ajankohtainen. Osku voisi soveltua kotiin, jossa on jo ennestään koira. Uskomme myös, että lapset eivät ole ongelma koska Osku ei vierasta ihmistä lainkaan.',
        dogHealthInfo:'Rokotettu, ja madotettu. Kastroidaan ennen Suomeen tuloa ja myös sirutetaan. Rekisteröidään ruokaviraston viranomaisrekisteriin.',
    },
]